owner = "eggstrom:"

[symlinks]
"~" = "files/home"
"~/.config/kitty/theme.conf" = "kitty-theme"
"~/.config/qt6ct/colors/catppuccin-mocha-blue.conf" = "qt-theme"
"~/.config/zathura/theme" = "zathura-theme"
