owner = "root:"

[files]
"/" = "files/root"
"~root" = "files/home"
"~root/.config/kitty/theme.conf" = "kitty-theme"
"~root/.config/qt6ct/colors/catppuccin-mocha-blue.conf" = "qt-theme"
"~root/.config/zathura/theme" = "zathura-theme"

[templates]
"/" = "templates/root"
